C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapCalculate_idx_in_frame (pts, plys, n_pts,
     & n_ply, idx, f2py_plys_d1)
      integer n_pts
      integer n_ply
      integer f2py_plys_d1
      real pts((n_pcd),2)
      real plys(n_ply,f2py_plys_d1)
      integer idx(n_pts)
      interface
      subroutine Calculate_idx_in_frame(pts,plys,n_pts,n_ply,idx) 
          real, dimension(n_pcd,2) :: pts
          real, dimension(n_ply,:) :: plys
          integer :: n_pts
          integer :: n_ply
          integer, dimension(n_pts) :: idx
      end subroutine Calculate_idx_in_frame
      end interface
      call Calculate_idx_in_frame(pts, plys, n_pts, n_ply, idx)
      end

