/* File: cn_PnPoly4module.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Thu Jun 18 06:38:48 2020
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include <stdarg.h>
#include "Python.h"
#include "fortranobject.h"
#include <string.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *cn_PnPoly4_error;
static PyObject *cn_PnPoly4_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(cn_PnPoly4_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = cn_PnPoly4_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
    PyArrayObject *arr = NULL;
    PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
    if (obj == Py_None) {
        if (*len == -1)
            *len = strlen(inistr); /* Will this cause problems? */
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,inistr,*len+1);
        return 1;
    }
    if (PyArray_Check(obj)) {
        if ((arr = (PyArrayObject *)obj) == NULL)
            goto capi_fail;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
            goto capi_fail;
        }
        if (*len == -1)
            *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
        return 1;
    }
    if (PyString_Check(obj)) {
        tmp = obj;
        Py_INCREF(tmp);
    }
#if PY_VERSION_HEX >= 0x03000000
    else if (PyUnicode_Check(obj)) {
        tmp = PyUnicode_AsASCIIString(obj);
    }
    else {
        PyObject *tmp2;
        tmp2 = PyObject_Str(obj);
        if (tmp2) {
            tmp = PyUnicode_AsASCIIString(tmp2);
            Py_DECREF(tmp2);
        }
        else {
            tmp = NULL;
        }
    }
#else
    else {
        tmp = PyObject_Str(obj);
    }
#endif
    if (tmp == NULL) goto capi_fail;
    if (*len == -1)
        *len = PyString_GET_SIZE(tmp);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
    Py_DECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = cn_PnPoly4_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(MAIN,MAIN)(int*,int*);
extern void F_FUNC_US(Cn_PnPoly_CC,CN_PNPOLY_CC)(float*,float*,int*,int*);
extern void F_FUNC_US(cn_PnPoly,CN_PNPOLY)(float*,float*,int*,int*);
extern void F_FUNC_US(Count_lines,COUNT_LINES)(string,int*,size_t);
extern void F_FUNC_US(LOAD_boundary,LOAD_BOUNDARY)(int*,float*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ MAIN ************************************/
static char doc_f2py_rout_cn_PnPoly4_MAIN[] = "\
MAIN(n_ply,r)\n\nWrapper for ``MAIN``.\
\n\nParameters\n----------\n"
"n_ply : input int\n"
"r : input int";
/* extern void F_FUNC(MAIN,MAIN)(int*,int*); */
static PyObject *f2py_rout_cn_PnPoly4_MAIN(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n_ply = 0;
  PyObject *n_ply_capi = Py_None;
  int r = 0;
  PyObject *r_capi = Py_None;
  static char *capi_kwlist[] = {"n_ply","r",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:cn_PnPoly4.MAIN",\
    capi_kwlist,&n_ply_capi,&r_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable n_ply */
    f2py_success = int_from_pyobj(&n_ply,n_ply_capi,"cn_PnPoly4.MAIN() 1st argument (n_ply) can't be converted to int");
  if (f2py_success) {
  /* Processing variable r */
    f2py_success = int_from_pyobj(&r,r_capi,"cn_PnPoly4.MAIN() 2nd argument (r) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n_ply,&r);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of r*/
  /* End of cleaning variable r */
  } /*if (f2py_success) of n_ply*/
  /* End of cleaning variable n_ply */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of MAIN ********************************/

/******************************** Cn_PnPoly_CC ********************************/
static char doc_f2py_rout_cn_PnPoly4_Cn_PnPoly_CC[] = "\
Cn_PnPoly_CC(P,V,r,[n_ply])\n\nWrapper for ``Cn_PnPoly_CC``.\
\n\nParameters\n----------\n"
"P : input rank-1 array('f') with bounds (2)\n"
"V : input rank-2 array('f') with bounds (n_ply,2)\n"
"r : input int\n"
"\nOther Parameters\n----------------\n"
"n_ply : input int, optional\n    Default: shape(V,0)";
/* extern void F_FUNC_US(Cn_PnPoly_CC,CN_PNPOLY_CC)(float*,float*,int*,int*); */
static PyObject *f2py_rout_cn_PnPoly4_Cn_PnPoly_CC(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *P = NULL;
  npy_intp P_Dims[1] = {-1};
  const int P_Rank = 1;
  PyArrayObject *capi_P_tmp = NULL;
  int capi_P_intent = 0;
  PyObject *P_capi = Py_None;
  float *V = NULL;
  npy_intp V_Dims[2] = {-1, -1};
  const int V_Rank = 2;
  PyArrayObject *capi_V_tmp = NULL;
  int capi_V_intent = 0;
  PyObject *V_capi = Py_None;
  int n_ply = 0;
  PyObject *n_ply_capi = Py_None;
  int r = 0;
  PyObject *r_capi = Py_None;
  static char *capi_kwlist[] = {"P","V","r","n_ply",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|O:cn_PnPoly4.Cn_PnPoly_CC",\
    capi_kwlist,&P_capi,&V_capi,&r_capi,&n_ply_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable r */
    f2py_success = int_from_pyobj(&r,r_capi,"cn_PnPoly4.Cn_PnPoly_CC() 3rd argument (r) can't be converted to int");
  if (f2py_success) {
  /* Processing variable P */
  P_Dims[0]=2;
  capi_P_intent |= F2PY_INTENT_IN;
  capi_P_tmp = array_from_pyobj(NPY_FLOAT,P_Dims,P_Rank,capi_P_intent,P_capi);
  if (capi_P_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(cn_PnPoly4_error,"failed in converting 1st argument `P' of cn_PnPoly4.Cn_PnPoly_CC to C/Fortran array" );
  } else {
    P = (float *)(PyArray_DATA(capi_P_tmp));

  /* Processing variable V */
  V_Dims[1]=2;
  capi_V_intent |= F2PY_INTENT_IN;
  capi_V_tmp = array_from_pyobj(NPY_FLOAT,V_Dims,V_Rank,capi_V_intent,V_capi);
  if (capi_V_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(cn_PnPoly4_error,"failed in converting 2nd argument `V' of cn_PnPoly4.Cn_PnPoly_CC to C/Fortran array" );
  } else {
    V = (float *)(PyArray_DATA(capi_V_tmp));

  /* Processing variable n_ply */
  if (n_ply_capi == Py_None) n_ply = shape(V,0); else
    f2py_success = int_from_pyobj(&n_ply,n_ply_capi,"cn_PnPoly4.Cn_PnPoly_CC() 1st keyword (n_ply) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(V,0)==n_ply,"shape(V,0)==n_ply","1st keyword n_ply","Cn_PnPoly_CC:n_ply=%d",n_ply) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(P,V,&n_ply,&r);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(V,0)==n_ply)*/
  } /*if (f2py_success) of n_ply*/
  /* End of cleaning variable n_ply */
  if((PyObject *)capi_V_tmp!=V_capi) {
    Py_XDECREF(capi_V_tmp); }
  }  /*if (capi_V_tmp == NULL) ... else of V*/
  /* End of cleaning variable V */
  if((PyObject *)capi_P_tmp!=P_capi) {
    Py_XDECREF(capi_P_tmp); }
  }  /*if (capi_P_tmp == NULL) ... else of P*/
  /* End of cleaning variable P */
  } /*if (f2py_success) of r*/
  /* End of cleaning variable r */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of Cn_PnPoly_CC ****************************/

/********************************* cn_PnPoly *********************************/
static char doc_f2py_rout_cn_PnPoly4_cn_PnPoly[] = "\
cn_PnPoly(P,V,r,[n])\n\nWrapper for ``cn_PnPoly``.\
\n\nParameters\n----------\n"
"P : input rank-1 array('f') with bounds (2)\n"
"V : input rank-2 array('f') with bounds (n,2)\n"
"r : input int\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: shape(V,0)";
/* extern void F_FUNC_US(cn_PnPoly,CN_PNPOLY)(float*,float*,int*,int*); */
static PyObject *f2py_rout_cn_PnPoly4_cn_PnPoly(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *P = NULL;
  npy_intp P_Dims[1] = {-1};
  const int P_Rank = 1;
  PyArrayObject *capi_P_tmp = NULL;
  int capi_P_intent = 0;
  PyObject *P_capi = Py_None;
  float *V = NULL;
  npy_intp V_Dims[2] = {-1, -1};
  const int V_Rank = 2;
  PyArrayObject *capi_V_tmp = NULL;
  int capi_V_intent = 0;
  PyObject *V_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int r = 0;
  PyObject *r_capi = Py_None;
  static char *capi_kwlist[] = {"P","V","r","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|O:cn_PnPoly4.cn_PnPoly",\
    capi_kwlist,&P_capi,&V_capi,&r_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable r */
    f2py_success = int_from_pyobj(&r,r_capi,"cn_PnPoly4.cn_PnPoly() 3rd argument (r) can't be converted to int");
  if (f2py_success) {
  /* Processing variable P */
  P_Dims[0]=2;
  capi_P_intent |= F2PY_INTENT_IN;
  capi_P_tmp = array_from_pyobj(NPY_FLOAT,P_Dims,P_Rank,capi_P_intent,P_capi);
  if (capi_P_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(cn_PnPoly4_error,"failed in converting 1st argument `P' of cn_PnPoly4.cn_PnPoly to C/Fortran array" );
  } else {
    P = (float *)(PyArray_DATA(capi_P_tmp));

  /* Processing variable V */
  V_Dims[1]=2;
  capi_V_intent |= F2PY_INTENT_IN;
  capi_V_tmp = array_from_pyobj(NPY_FLOAT,V_Dims,V_Rank,capi_V_intent,V_capi);
  if (capi_V_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(cn_PnPoly4_error,"failed in converting 2nd argument `V' of cn_PnPoly4.cn_PnPoly to C/Fortran array" );
  } else {
    V = (float *)(PyArray_DATA(capi_V_tmp));

  /* Processing variable n */
  if (n_capi == Py_None) n = shape(V,0); else
    f2py_success = int_from_pyobj(&n,n_capi,"cn_PnPoly4.cn_PnPoly() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(V,0)==n,"shape(V,0)==n","1st keyword n","cn_PnPoly:n=%d",n) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(P,V,&n,&r);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(V,0)==n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  if((PyObject *)capi_V_tmp!=V_capi) {
    Py_XDECREF(capi_V_tmp); }
  }  /*if (capi_V_tmp == NULL) ... else of V*/
  /* End of cleaning variable V */
  if((PyObject *)capi_P_tmp!=P_capi) {
    Py_XDECREF(capi_P_tmp); }
  }  /*if (capi_P_tmp == NULL) ... else of P*/
  /* End of cleaning variable P */
  } /*if (f2py_success) of r*/
  /* End of cleaning variable r */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of cn_PnPoly ******************************/

/******************************** Count_lines ********************************/
static char doc_f2py_rout_cn_PnPoly4_Count_lines[] = "\
Count_lines(filename,n_ply)\n\nWrapper for ``Count_lines``.\
\n\nParameters\n----------\n"
"filename : input string(len=100)\n"
"n_ply : input int";
/* extern void F_FUNC_US(Count_lines,COUNT_LINES)(string,int*,size_t); */
static PyObject *f2py_rout_cn_PnPoly4_Count_lines(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,int*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string filename = NULL;
  int slen(filename);
  PyObject *filename_capi = Py_None;
  int n_ply = 0;
  PyObject *n_ply_capi = Py_None;
  static char *capi_kwlist[] = {"filename","n_ply",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:cn_PnPoly4.Count_lines",\
    capi_kwlist,&filename_capi,&n_ply_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable n_ply */
    f2py_success = int_from_pyobj(&n_ply,n_ply_capi,"cn_PnPoly4.Count_lines() 2nd argument (n_ply) can't be converted to int");
  if (f2py_success) {
  /* Processing variable filename */
  slen(filename) = 100;
  f2py_success = string_from_pyobj(&filename,&slen(filename),"",filename_capi,"string_from_pyobj failed in converting 1st argument `filename' of cn_PnPoly4.Count_lines to C string");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(filename,&n_ply,slen(filename));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    STRINGFREE(filename);
  }  /*if (f2py_success) of filename*/
  /* End of cleaning variable filename */
  } /*if (f2py_success) of n_ply*/
  /* End of cleaning variable n_ply */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of Count_lines *****************************/

/******************************* LOAD_boundary *******************************/
static char doc_f2py_rout_cn_PnPoly4_LOAD_boundary[] = "\
LOAD_boundary(plys,[n_ply])\n\nWrapper for ``LOAD_boundary``.\
\n\nParameters\n----------\n"
"plys : input rank-2 array('f') with bounds (n_ply,2)\n"
"\nOther Parameters\n----------------\n"
"n_ply : input int, optional\n    Default: shape(plys,0)";
/* extern void F_FUNC_US(LOAD_boundary,LOAD_BOUNDARY)(int*,float*); */
static PyObject *f2py_rout_cn_PnPoly4_LOAD_boundary(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n_ply = 0;
  PyObject *n_ply_capi = Py_None;
  float *plys = NULL;
  npy_intp plys_Dims[2] = {-1, -1};
  const int plys_Rank = 2;
  PyArrayObject *capi_plys_tmp = NULL;
  int capi_plys_intent = 0;
  PyObject *plys_capi = Py_None;
  static char *capi_kwlist[] = {"plys","n_ply",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O|O:cn_PnPoly4.LOAD_boundary",\
    capi_kwlist,&plys_capi,&n_ply_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable plys */
  plys_Dims[1]=2;
  capi_plys_intent |= F2PY_INTENT_IN;
  capi_plys_tmp = array_from_pyobj(NPY_FLOAT,plys_Dims,plys_Rank,capi_plys_intent,plys_capi);
  if (capi_plys_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(cn_PnPoly4_error,"failed in converting 1st argument `plys' of cn_PnPoly4.LOAD_boundary to C/Fortran array" );
  } else {
    plys = (float *)(PyArray_DATA(capi_plys_tmp));

  /* Processing variable n_ply */
  if (n_ply_capi == Py_None) n_ply = shape(plys,0); else
    f2py_success = int_from_pyobj(&n_ply,n_ply_capi,"cn_PnPoly4.LOAD_boundary() 1st keyword (n_ply) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(plys,0)==n_ply,"shape(plys,0)==n_ply","1st keyword n_ply","LOAD_boundary:n_ply=%d",n_ply) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n_ply,plys);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(plys,0)==n_ply)*/
  } /*if (f2py_success) of n_ply*/
  /* End of cleaning variable n_ply */
  if((PyObject *)capi_plys_tmp!=plys_capi) {
    Py_XDECREF(capi_plys_tmp); }
  }  /*if (capi_plys_tmp == NULL) ... else of plys*/
  /* End of cleaning variable plys */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of LOAD_boundary ****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"MAIN",-1,{{-1}},0,(char *)F_FUNC(MAIN,MAIN),(f2py_init_func)f2py_rout_cn_PnPoly4_MAIN,doc_f2py_rout_cn_PnPoly4_MAIN},
  {"Cn_PnPoly_CC",-1,{{-1}},0,(char *)F_FUNC_US(Cn_PnPoly_CC,CN_PNPOLY_CC),(f2py_init_func)f2py_rout_cn_PnPoly4_Cn_PnPoly_CC,doc_f2py_rout_cn_PnPoly4_Cn_PnPoly_CC},
  {"cn_PnPoly",-1,{{-1}},0,(char *)F_FUNC_US(cn_PnPoly,CN_PNPOLY),(f2py_init_func)f2py_rout_cn_PnPoly4_cn_PnPoly,doc_f2py_rout_cn_PnPoly4_cn_PnPoly},
  {"Count_lines",-1,{{-1}},0,(char *)F_FUNC_US(Count_lines,COUNT_LINES),(f2py_init_func)f2py_rout_cn_PnPoly4_Count_lines,doc_f2py_rout_cn_PnPoly4_Count_lines},
  {"LOAD_boundary",-1,{{-1}},0,(char *)F_FUNC_US(LOAD_boundary,LOAD_BOUNDARY),(f2py_init_func)f2py_rout_cn_PnPoly4_LOAD_boundary,doc_f2py_rout_cn_PnPoly4_LOAD_boundary},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "cn_PnPoly4",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_cn_PnPoly4(void) {
#else
#define RETVAL
PyMODINIT_FUNC initcn_PnPoly4(void) {
#endif
  int i;
  PyObject *m,*d, *s, *tmp;
#if PY_VERSION_HEX >= 0x03000000
  m = cn_PnPoly4_module = PyModule_Create(&moduledef);
#else
  m = cn_PnPoly4_module = Py_InitModule("cn_PnPoly4", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module cn_PnPoly4 (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  Py_DECREF(s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'cn_PnPoly4' is auto-generated with f2py (version:2).\nFunctions:\n"
"  MAIN(n_ply,r)\n"
"  Cn_PnPoly_CC(P,V,r,n_ply=shape(V,0))\n"
"  cn_PnPoly(P,V,r,n=shape(V,0))\n"
"  Count_lines(filename,n_ply)\n"
"  LOAD_boundary(plys,n_ply=shape(plys,0))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  Py_DECREF(s);
  cn_PnPoly4_error = PyErr_NewException ("cn_PnPoly4.error", NULL, NULL);
  /*
   * Store the error object inside the dict, so that it could get deallocated.
   * (in practice, this is a module, so it likely will not and cannot.)
   */
  PyDict_SetItemString(d, "_cn_PnPoly4_error", cn_PnPoly4_error);
  Py_DECREF(cn_PnPoly4_error);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }





/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"cn_PnPoly4");
#endif
  return RETVAL;
}
#ifdef __cplusplus
}
#endif
